name: Auto Prettify

on:
  push:
    branches:
      - master

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.1
      - run: yarn
      - run: yarn prettify
      - name: "Commit prettier changes"
        run: |
          git config user.name 'credbot'
          git config user.email '42819382+credbot@users.noreply.github.com'
          git add .
          git commit --allow-empty -m "Run prettier"
      - name: "Preview committed changes"
        run: git show
      - name: "Push changes"
        run: git push
